### ISSUE TITLE
Account Blank

### ISSUE THREAD

**Issue by team3cord** [Topher84/NetSuite-Tools-For-WebStorm#11]
Excited to try the plugin. I'm having issues getting it configured.  

It's for a Sandbox account. When try to set up a project and enter my email, pw && env on the next step the Account section is empty and I cant add/edit it.

Am I missing some step?

Thanks for the help.

~ Matt C

**Comment by Topher84** [comment]
Hi Matt, glad you wanting to get away from Eclipse 👍 

Once you've entered your NetSuite e-mail/password, the "account selection" makes a call to NetSuite's "REST roles webservice" that is then parsed for the accounts which your role has either A) Administrator or B) Full Access. If you don't have either of those, then there won't be anything to select. I would verify your role(s) in the Sandbox account. If you want to make the call yourself to see what is being pulled back, you can see SuiteAnswers: 24424 "Using the REST roles Service to Get User Accounts, Roles, and Domains" which has a ton of info and examples on how to call it.

Since you are getting to the accounts window, your e-mail/password is most likely correct as well or you would (should at least) be receiving a popup stating that accounts could not be retrieved. 

If you see that you have accounts that have either of those roles that are not being put in the list, please let me know and i'll see if I can help further.

**Comment by team3cord** [comment]
Thanks for the quick response. I have a lesser role on our account. I will see if I can get it updated.
I appreciate the help.

**Comment by sclearion** [comment]
I am getting this issue too. I can login with the Eclipse plugin with the same credentials, how ever using this plugin, the accounts fields is now blank. I am the admin of the acct. I do not think your service us calling the same roles url or there is some abstraction in between

**Comment by Topher84** [comment]
@sclearion I would suggest you call the roles rest service with your information and see what roles are available to you. I would be fairly confident it is still a permissions error. If you do that and you are seeing the roles returned from the service but not in the plugin, feel free to open an issue.
