### ISSUE TITLE
Uploading only changed files

### ISSUE THREAD

**Issue by petrmaly12** [Topher84/NetSuite-Tools-For-WebStorm#12]
Hi, I just want to ask, if there could be a way how to determine which files were really changed since last upload and to upload just these ones? It will speed up whole uploading process and also DEVs shouldn't take care about particular files and could just upload whole branch every time.

**Comment by Topher84** [comment]
Hi,

Comparing the files that have changed against the file cabinet would take a trip to get the file and then programmatically compare it and then if different, upload the file. It would be at least twice as slow as just uploading the file. Your best option right now is to just upload it all (if you're sure you want to do that) until NetSuite
releases their SDF command line utility so I can see what i can do to improve since SDF works better with version control. Their web service is not the fastest thing for sure, but there's nothing I can do about that currently.

Another scenario I run into is multiple people working on the same file(s) (Different companies, or users that may not have access to the same repo... believe me it happens) Maybe I don't want to upload my changes just because they are differen since that may mess up the other person. I would say blindly uploading an entire branch may be a bad idea unless you're a 1 person shop that is very confident or are certain your changes are the ONLY changes.

**Comment by petrmaly12** [comment]
Thanks for quick reply, got it. Looking forward to SDF CLI support. I was hoping it might speed up uploading process in case you have one code branch on which is working whole team and at some point you want to upload edited/added files to some account so you wouldn't have to care about which files were updated and you could just upload whole branch. But from what you're saying, it would be much slower. Thanks again.
