### ISSUE TITLE
(Request) Ability to save both  Sandbox and Production username/password/ folder path 

### ISSUE THREAD

**Issue by RezaSeedin** [Topher84/NetSuite-Tools-For-WebStorm#18]
Hi Chris,

Could you add the functionality to save both Sandbox and Production details (username/password/ folder path) so it can be easily switched. This would be a great feature to add.

Love this tool and keep up the good work 👍 🥇 

Regards

Reza

**Comment by Topher84** [comment]
Hi Reza,

Thank you for the kind words. Glad to see you are getting some use out of it.

Projects are setup on an account type basis. So you should be able to have a project for the sandbox and a project for the production environment and easily switch between them via the IDE by closing the current project and opening the sandbox project. I would suggest multiple projects so that you know which environment you are in and are not taking a guess at "am I in prod? or sb?".

**Comment by RezaSeedin** [comment]
Hi @Topher84 , Currently I use empty project (I'm assuming that's what everyone does). I create a new project on the same path that I used before It picks up the same settings from the .idea folder. 

Is there something I can do to get around it.
Steps
1. Create new project **D:\TESTING\My project** (name project PROD PROJECT)
2. If I go create new project and give the same path Webstrom picks up the settings from the folder
3. renaming the project over rights any settings

Do you have 2 separate folders for PROD and SB?

**Comment by Topher84** [comment]
You would have 2 projects:

1. D:\TESTING\My Project PROD
 - This would have specific settings for prod
2. D:\TESTING\My Project SB
 - This would have specific settings for sb

2 different directories. Otherwise you can right click a project, change the settings and just switch the root to whatever you want. I personally do not switch back and forth between a prod and sandbox a lot. If I do, I just change settings to that environment via change settings.

**Comment by RezaSeedin** [comment]
Got it thanks. Currently, my company will only have 1 folder per customer as its synced with GIT hence my initial request

If you are looking to add new features for your next version hope this makes the cut :)

**Comment by Topher84** [comment]
That's how my projects are set up as well. 1 customer 1 git repo. You can still do either option I gave and it should have 0 issue with git.

**Comment by Topher84** [comment]
Going to close this for now as going forward with the new domain system, there isn't any differentiation between sandbox and production in regards to logging in and you just log into production and choose the account you want so I don't think there needs to be anything done specifically for this. I will however, make an adjustment in the future to support the domain system.
