### ISSUE TITLE
Prompt on password change

### ISSUE THREAD

**Issue by Ruplahlava** [Topher84/NetSuite-Tools-For-WebStorm#25]
Hello,
can there be some prompt, that NSTools cant connect or something?

When you change your password in NS and then you try to upload something with previously saved project settings, it does nothing, no error in console, nothing.

**Comment by Topher84** [comment]
I can take a look at my code but I am pretty sure I am checking for errors on login and displaying that. If NetSuite doesn't throw an error, there's no way for me to know that you've changed your password in NetSuite. I have not seen this error myself as I've had to change my password before and when trying to upload I would get an error saying that it couldn't log in. I am assuming that you changed your credentials via project settings and haven't had any issues since though correct?

**Comment by Ruplahlava** [comment]
Hmm, tried it a few times before writing this ticket. No error was shown.
But you are right, after changing project settings i had no issue like this, every prompt like file uploaded is being shown.

**Comment by Topher84** [comment]
I'll close this for now as it seems to be resolved. I'll investigate this some more when I do my next release to see if there's anything else I can do.
