### ISSUE TITLE
Error Logging In

### ISSUE THREAD

**Issue by ghost** [Topher84/NetSuite-Tools-For-WebStorm#31]
Having trouble logging in after a sandbox refresh. (Eclipse WSDL plugin still works). I have been using this plugin for over a year with no issues so not sure what I can do to fix

Using version 1.1.0 we take the following steps to get this error

1. Netsuite Tools > Setup Project
2. Enter email, password & select Sandbox
3. Select account from the **Account Selection** screen
4. **Error Logging** In pops up immediately but still lets me see the **File Cabinet** window when I close the error

- Password has not changed nor has my email and all other WSDL based plugins to Netsuite work

**Comment by Topher84** [comment]
Someone had this issue the other day with logging in and it eventually went away. There's gotta be something that happens on sandbox refresh that isn't playing nicely. I would give it a few and retry. The file cabinet screen popping up is because I don't bail if there's an error (which I should be doing).

**Comment by xpeltech** [comment]
Do you hard-set the ROLE ID on the **Account Selection** screen to Administrator = 3. Reason I ask is that my default role is **Dev Ops Manager**, a custom role, not netsuite's native **Administrator** so that could explain the login error Im getting

**Comment by xpeltech** [comment]
Nevermind, I answered my own question: I see on NSRolesRestServiceController.java on line 14 that there are some hardcoded properties
