### ISSUE TITLE
Upload issue on 2018.2

### ISSUE THREAD

**Issue by Ruplahlava** [Topher84/NetSuite-Tools-For-WebStorm#38]
![image](https://user-images.githubusercontent.com/4836841/43724596-a6c4c5d8-999a-11e8-894d-bff4347a9d37.png)
We encountered this issue, after update to 2018.2
File is not uploaded, plugin not working...

**Comment by Topher84** [comment]
I've been using 2018.2 WebStorm and have had no issue since release. Are you sure this isn't a data related issue with your specific instance? Are you still seeing this issue?

**Comment by Ruplahlava** [comment]
Sorry, the versioning. I meant Netsuite version 2018.2

**Comment by Topher84** [comment]
Is 2FA active? if so, the current plugin will work with 2FA as it uses login/pass. I am looking into changing to TBA but there is no ETA.

**Comment by n3xtgen** [comment]
It's not about 2FA, we have that turned off, we understand that it cannot work with it. Seems that I fixed the problem or it's at least a temporary fix if you can come up with better solution, because I just found the quickest solution I could, with regard to my very limited knowledge about SuiteTalk and SOAP in general, I will fill push request shortly.

**Comment by n3xtgen** [comment]
I submitted pull request #39 which should fix this issue.
The problem is that for some reason after this week's Netsuite 2018.2 Phase 0 release, authentication approach through "login" SOAP call and then using received JSESSIONID in immediate consecutive calls leads to error "Connection timed out. Please log in again." It may be a bug.
However, looking for this error on the internet I read somewhere that safer approach is to include authentication header ("passport") in every request, and it helped.

**Comment by Topher84** [comment]
Thanks! I'll take a look at the PR and see if it still works for me as well. You're the only ones that I've had report this so it may very well be a bug.

**Comment by Ruplahlava** [comment]
Bump? :)

**Comment by Topher84** [comment]
Working on re-write with Java 10 as we speak.

**Comment by Topher84** [comment]
I just released version 1.1.2 which has this fix and 2018.1 records browser link as thats the latest records browser. I'm not sure how long it'll take the plugin repository to update but it should be there shortly.

**Comment by Ruplahlava** [comment]
Fixed!
