### ISSUE TITLE
Unable to use plugin when account requires 2 factor authentication

### ISSUE THREAD

**Issue by zsatan** [Topher84/NetSuite-Tools-For-WebStorm#41]
Just says Error logging in : null.

I've attempted to create a new role and use that but the plugin seems to only recognise administrator

**Comment by Topher84** [comment]
2FA is not currently supported. I am currently working on an update to introduce token based authentication (TBA) instead of user/pass.

**Comment by owieboy** [comment]
Will it be possible to pull non-admin roles that don't require 2FA but has all necessary permissions (file cabinet and web service) and use that as account role in project setting instead?

**Comment by Topher84** [comment]
This is resolved in the latest version for now via creating a custom role that can upload. I was going to do TBA but I do not have time for that currently.

**Comment by GeekyAbhay** [comment]
Hi Chris,
Can you please let me know how to login using TBA in NetSuite in SuiteTalk?

Thanks,
Abhay

**Comment by Topher84** [comment]
As the above states, you need to create a custom role with the permission you need and assign it to your login so that you can log in.

Required Permissions (there are 3 total across 2 separate sublists):

1. Lists -> Documents and Files -> Full
2. Setup -> Allow JS/HTML Uploads -> Full
3. Setup -> Web Services -> Full

Assign that role to your login and you should see it when you log in w/ the plugin and you're good to go.
